UPDATE `shop_settings` SET `Value` = 'leogroup.com.ua | опис [OriginName] [ProductModel] [ProductName], купити [OriginName] [ProductModel] [ProductName] в Львові, Києві, Україна, опис, обзор, характеристики, ціна [OriginName] [ProductModel].',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'ProductKeywords';
UPDATE `shop_settings` SET `Value` = 'побутова техніка, техінка [CategoryName], купити [CatalogFirst5ProductNames], виробники [CatalogFirst5OriginNames], опис [CatalogFirst5ProductModels], ціни',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'CategoryKeywords';
UPDATE `shop_settings` SET `Value` = 'інтернет магазин, купити дешево, техніка, духовка, холодильник дешево, телевізори в Києві, пральні машинки, дешева техніка, побутова техніка по Україіні, леогруп, leogroup.com.ua, техніка з доставкою по Україіні, [CatalogFirst10OriginNames], [CatalogFirst10CategoryNames]',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'HomePageKeywords';
UPDATE `shop_settings` SET `Value` = '[OriginName] [ProductModel] в інтернет-магазині leogroup.com.ua. Доставка по Україіні, гарантія, знижки та сервіс! Купити [OriginName] [ProductModel] [ProductName].',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'ProductDescription';
UPDATE `shop_settings` SET `Value` = 'Всі [CategoryName] у Львів, Київ, Одеса, Харків, купити [CatalogFirst5ProductNames],  [CatalogFirst5OriginNames], опис [CatalogFirst5ProductModels], ціни, гарантія, доставка по Україні',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'CategoryDescription';
UPDATE `shop_settings` SET `Value` = 'Інтернет магазин побутової техніки leogroup.com.ua. Пральні машини, пилососи, духовки, холодильники, тостери, міксери, кавомашини в Львові. Доставка по Україні. Сервіс, гарантія та великий вибір побутової техніки за низькими цінами.',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'HomePageDescription';
UPDATE `shop_settings` SET `Value` = 'leogroup.com.ua | [OriginName] [ProductModel] [ProductName]. Ціна, купити [OriginName] [ProductModel] [ProductName] в Львові, Києві, доставка по Україіні. [CategoryName] [OriginName] [ProductModel] [ProductName] опис, обзор, характеристики, ціна, купити.',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'ProductPageTitle';
UPDATE `shop_settings` SET `Value` = 'Всі [CategoryName] - інтернет магазин leogroup.com.ua | Купити [CategoryName] в Україні з доставкою, дешево: ціни, опис, характеристики',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'CategoryPageTitle';
UPDATE `shop_settings` SET `Value` = 'Інтернет магазин сучаної побутової техніки leogroup.com.ua | Найдешевші ціни, доставка, гарантія, сервіс',`Status` = 'ACTIVE',`Type` = 'SEO',`DateUpdated` = NOW() WHERE `shop_settings`.`Property` = 'HomePageTitle';
