INSERT INTO `mpws_customer` 
            (`id`, 
             `hostname`, 
             `homepage`, 
             `title`, 
             `admintitle`, 
             `logo`, 
             `lang`, 
             `locale`, 
             `protocol`, 
             `plugins`, 
             `status`, 
             `datecreated`, 
             `dateupdated`) 
VALUES      (1, 
             'pb.com.ua', 
             'http://pb.com.ua', 
             'LEOGROUP', 
             'leogroup22', 
             '142351283954d915074d95a.png', 
             'ua', 
             'ua_uk', 
             'http', 
             'system,shop', 
             'ACTIVE', 
             '2014-11-18 11:02:37', 
             '2015-03-17 08:56:53'); 

INSERT INTO `mpws_users` 
            (`id`, 
             `customerid`, 
             `isonline`, 
             `firstname`, 
             `lastname`, 
             `email`, 
             `phone`, 
             `password`, 
             `validationstring`, 
             `status`, 
             `datelastaccess`, 
             `datecreated`, 
             `dateupdated`) 
VALUES      (1, 
             1, 
             1, 
             'Super', 
             'Admin', 
             'admin@mpws.ua', 
             '(000) 000-00-00', 
             'b2cff1386ea9cb5744731ac8e0d299dd', 
             '8de111e04ec15fc171c7723caa5342e2', 
             'ACTIVE', 
             '2014-11-18 11:02:37', 
             '2014-11-18 11:02:37', 
             '2014-11-18 11:02:37'); 

INSERT INTO `mpws_permissions` 
            (`id`, 
             `userid`, 
             `canadmin`, 
             `cancreate`, 
             `canedit`, 
             `canupload`, 
             `canviewreports`, 
             `canaddusers`, 
             `canmaintain`, 
             `dateupdated`, 
             `datecreated`) 
VALUES      (1, 
             1, 
             1, 
             1, 
             1, 
             0, 
             1, 
             0, 
             1, 
             '2014-11-18 11:02:37', 
             '2014-11-18 11:02:37'); 